# Some plugins use /info for things. This let's you change the plugins command so they don't override.
# Default is /info.
info-command-override: "info"

# This is the start date of your world.
# Format: MM/DD/YYYY. You must put zeros for single digits. Example: 06, 02, 01, etc.
date: 05/27/2019 # This date is May 27th, 2019.

# Some servers have different folder names for the worlds. Please update these to match yours.
# Leave default if you didn't change the names.
world-files:
  overworld: "world"
  nether: "world_nether"
  end: "world_the_end"

# This is where you can change what message is on the command.
# {{STARTDATE}} - Displays the start date for the server. Uses the date above.
# {{DAYS}} - Displays how many days since the start date for the server.
# {{WORLDSIZE}} - Displays the world size.
# {{TOTALJOINS}} - Displays the total unique players that have joined.
command-message:
  - "&6--------------------------------------------"
  - "&3ServerName was created on {{STARTDATE}}. That was {{DAYS}} days ago."
  - "&3The world is {{WORLDSIZE}}."
  - "&3A total of {{TOTALJOINS}} players have joined."
  - "&6--------------------------------------------"