name: AnarchyStats
version: ${project.version}
main: lol.hyper.anarchystats.AnarchyStats
api-version: 1.15
load: STARTUP
author: hyperdefined
commands:
  info:
    description: See world information.
  anarchystats:
    description: Main command.